$yml = @"
name: Deploy WWTC Mumbai
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install AWS CLI v2
      - name: Install AWS CLI v2
        run: |
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      # Install PowerShell 7
      - name: Install PowerShell 7
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y
          sudo apt-get install -y powershell
          pwsh -v

      # Show OIDC token claims
      - name: Show OIDC token claims (debug)
        uses: actions/github-script@v7
        with:
          script: |
            const id = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(Buffer.from(id.split('.')[1], 'base64').toString());
            console.log('OIDC aud:', payload.aud);
            console.log('OIDC sub:', payload.sub);

      # Configure AWS via OIDC
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::965276659689:role/GHActionsDeployRole
          aws-region: ap-south-1

      - name: Who am I in AWS?
        run: aws sts get-caller-identity

      - name: Smoke payload
        run: |
          cat > invoke_event_body.json <<'JSON'
          {
            "pathParameters": { "serviceCode": "ttt", "sourceLanguageCode": "en-US", "targetLanguageCode": "es-ES" },
            "queryStringParameters": null,
            "httpMethod": "POST",
            "body": "{\"text\":\"hello world\"}",
            "headers": { "Content-Type": "application/json" }
          }
          JSON

      - name: Deploy
        run: pwsh -NoLogo -NoProfile -File ./ops/deploy.ps1
"@
Set-Content .github\workflows\deploy.yml -Encoding utf8 -Value $yml