name: Deploy WWTC Mumbai
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install AWS CLI v2 the supported way (NO apt)
      - name: Setup AWS CLI
        uses: aws-actions/setup-aws-cli@v4

      # Install PowerShell 7 on the runner
      - name: Setup PowerShell
        uses: PowerShell/actions-setup-powershell@v2
        with:
          powershell-version: '7.4.x'

      # Configure AWS creds via OIDC, assumes your role in 965276659689
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::965276659689:role/GHActionsDeployRole
          aws-region: ap-south-1

      - name: Who am I in AWS?
        run: aws sts get-caller-identity

      - name: Smoke payload
        run: |
          cat > invoke_event_body.json <<'JSON'
          {
            "pathParameters": { "serviceCode": "ttt", "sourceLanguageCode": "en-US", "targetLanguageCode": "es-ES" },
            "queryStringParameters": null,
            "httpMethod": "POST",
            "body": "{\"text\":\"hello world\"}",
            "headers": { "Content-Type": "application/json" }
          }
          JSON

      # Run your PowerShell deploy script (no --profile in CI)
      - name: Deploy
        shell: pwsh
        run: ./ops/deploy.ps1