name: Deploy WWTC Mumbai
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # -------- No marketplace actions below --------
      # Install AWS CLI v2 (official bundle)
      - name: Install AWS CLI v2
        shell: bash
        run: |
          set -euo pipefail
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      # Install PowerShell 7 (adds MS repo then apt installs)
      - name: Install PowerShell 7
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y
          sudo apt-get install -y powershell
          pwsh -v

      # OIDC: assume your deploy role (this action has been resolving fine)
            - name: Show OIDC token claims (debug)
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const id = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(Buffer.from(id.split('.')[1], 'base64').toString());
            console.log('OIDC aud:', payload.aud);
            console.log('OIDC sub:', payload.sub);
- name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::965276659689:role/GHActionsDeployRole
          aws-region: ap-south-1

      - name: Who am I in AWS?
        run: |
          aws sts get-caller-identity

      - name: Smoke payload
        shell: bash
        run: |
          cat > invoke_event_body.json <<'JSON'
          {
            "pathParameters": { "serviceCode": "ttt", "sourceLanguageCode": "en-US", "targetLanguageCode": "es-ES" },
            "queryStringParameters": null,
            "httpMethod": "POST",
            "body": "{\"text\":\"hello world\"}",
            "headers": { "Content-Type": "application/json" }
          }
          JSON

      # Run your deploy script with PowerShell
      - name: Deploy
        shell: bash
        run: pwsh -NoLogo -NoProfile -File ./ops/deploy.ps1

