name: Deploy WWTC Mumbai
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - name: Install awscli & powershell
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli powershell
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::965276659689:role/GHActionsDeployRole
          aws-region: ap-south-1
      - name: Smoke payload
        run: |
          cat > invoke_event_body.json <<'JSON'
          {
            "pathParameters": { "serviceCode": "ttt", "sourceLanguageCode": "en-US", "targetLanguageCode": "es-ES" },
            "queryStringParameters": null,
            "httpMethod": "POST",
            "body": "{\"text\":\"hello world\"}",
            "headers": { "Content-Type": "application/json" }
          }
          JSON
      - name: Deploy
        shell: pwsh
        run: ./ops/deploy.ps1
